name: Bug report
description: Report a bug that you found, e.g. something is not working as expected
# title: ""
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for helping us to improve the driver!

        In the case you have difficulties to write in english, try the [deepl.com](https://www.deepl.com) translator.

        ## 🚨 IMPORTANT 🚨

        * Please carefully read all the instructions below including the descriptions! Very often we have to request the data again, because it was not provided in the first place.

        * Please try the `nightly` build first, if you are not already using it. It's very likely that the bug is already fixed. See [here](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/general/install#nightly-build) how to install it.

        * Did you reboot at least once after you saw the issue? If not, reboot and check if the issue still exists.

        * Please read the complete [changelog](https://github.com/mr-manuel/dbus-serialbattery/blob/master/CHANGELOG.md).

        * Make sure to provide the logfiles in the correct format with a HUMAN READABLE timestamp by piping the output through `tai64nlocal`. See [here](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/#driver-log-files) how to get the driver log files.

          Wrong: `@4000000067d9220b2652dc14`

          Correct: `2025-03-18 07:34:25.642964500`

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Paste also screenshots and pictures, if needed. The more informations you give, the faster we find a solution.
      placeholder: |
        NOTE: Paste the logfields in the appropriate field below.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Please describe in clear steps how to reproduce the issue. Paste also screenshots, if needed.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. Paste also screenshots, if needed.
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Installation method
      description: Select how you installed the driver.
      multiple: false
      options:
        - ⚠️ Choose your option ⚠️
        - Install script from the documentation
        - Install script present in the driver folder
        - SFTP upload
        - USB stick
        - Other (please describe in the last textfield how you installed the driver)
    validations:
      required: true

  - type: input
    id: driver_version_installed
    attributes:
      label: Driver version of the currently installed driver
      description: |
        Visible in the [driver log files](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/#driver-log-files) or in the remote console/GUI under `SerialBattery` -> `Device` -> `Firmware version`.

        ⚠️ **IMPORTANT:** Do not write `latest` and specify the exact version number, else we cannot help you.
      placeholder: e.g. v1.0.20230927beta
    validations:
      required: true

  - type: input
    id: driver_version_last_working
    attributes:
      label: Driver version of the last known working driver
      description: |
        Insert the version of the driver where the bug was not present. If you don't know, leave it empty.
      placeholder: e.g. v1.0.20230927beta
    validations:
      required: false

  - type: dropdown
    id: venus_os_device_type
    attributes:
      label: Venus OS device type
      description: Select your Venus OS device type.
      multiple: false
      # https://github.com/victronenergy/venus/wiki/machines
      options:
        - ⚠️ Choose your option ⚠️
        - CCGX
        - Cerbo GX
        - Ekrano GX
        - GX Card (integrated in the Victron device)
        - Octo GX
        - Raspberry Pi 2
        - Raspberry Pi 3
        - Raspberry Pi 4
        - Raspberry Pi 5
        - Raspberry Pi Zero 2W
        - Raspberry Pi Zero
        - VANcu GX
        - Venus_GX
    validations:
      required: true

  - type: input
    id: venus_os_version
    attributes:
      label: Venus OS version
      description: |
        Visible in the remote console/GUI under `Settings` -> `Firmware` -> `Firmware version`

        ⚠️ **IMPORTANT:** Do not write `latest` and specify the exact version number, else we cannot help you.
      placeholder: e.g. v3.60
    validations:
      required: true

  - type: dropdown
    id: venus_os_image_type
    attributes:
      label: Venus OS image type
      description: Select your Venus OS image type. Can be found in the remote console/GUI under `Settings` -> `General` -> `Firmware` -> `Online updates` -> `Image type`.
      multiple: false
      options:
        - ⚠️ Choose your option ⚠️
        - Normal
        - Large
    validations:
      required: true

  - type: dropdown
    id: bms_type
    attributes:
      label: BMS type
      description: Select your used BMS type.
      multiple: true
      # https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/general/supported-bms
      options:
        - ANT BMS
        - Daly BMS
        - Daren 485
        - ECS GreenMeter
        - EG4 LiFePower (Revov, Tian Power)
        - EG4 LL
        - Felicity
        - Hektec Modbus SmartBMS / YanYang BMS
        - HLPdata BMS4S
        - Jiabaida JDB BMS (LLT Power, Overkill Solar, Smart BMS)
        - JKBMS (Heltec BMS)
        - JKBMS Inverter (JKBMS PB Model)
        - Kilovault
        - KS48100
        - LiTime
        - MNB spi BMS
        - Pace BMS
        - Renogy BMS
        - Seplos
        - Seplos v3
        - Sinowealth
        - Valence U-BMS
    validations:
      required: true

  - type: input
    id: cell_count
    attributes:
      label: Cell count
      description: Specify how many cells your battery has.
    validations:
      required: true

  - type: input
    id: battery_count
    attributes:
      label: Battery count
      description: Specify how many batteries/BMS are connected to your Venus OS.
    validations:
      required: true

  - type: dropdown
    id: connection_type
    attributes:
      label: Connection type
      description: Select how you connected your battery to the Venus OS device.
      multiple: false
      options:
        - ⚠️ Choose your option ⚠️
        - Serial USB adapter to TTL
        - Serial USB adapter to RS485
        - Raspberry Pi RS485 HAT
        - Bluetooth
        - CAN
    validations:
      required: true

  - type: dropdown
    id: usb_hub
    attributes:
      label: USB hub
      description: |
        Select if you use a USB hub to connect the Serial USB adapter to the Venus OS device.

        ⚠️ **IMPORTANT:** If you use a USB hub, try to connect the Serial USB adapter directly to the Venus OS device to see if the issue still exists.
      multiple: false
      options:
        - "⚠️ Choose your option ⚠️"
        - "No, the Serial USB adapter is connected directly to the Venus OS device"
        - "Yes, no external power supply"
        - "Yes, with external power supply"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Config file
      description: |
        Paste your `config.ini` file here. See [here](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/general/install#settings-locationpath) where you can find it. DO NOT COPY the `config.default.ini` here. The content will be automatically formatted into code, so no need for tripple backticks.
      render: ini
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output here. See [here](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/#driver-log-files) how to get the driver log files. The content will be automatically formatted into code, so no need for tripple backticks.

        ⚠️ **IMPORTANT:** Do not forget to pipe the output through `tai64nlocal`, if you don't copy the commands from the documentation.
      render: shell
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
      description: If you are using a USB hub, paste a link to it here. Leave empty, if you already said all.

  - type: checkboxes
    id: read_instructions
    attributes:
      label: Please confirm that you have completed the following steps before submitting your support request
      options:
        - label: 'I have carefully read all the instructions above including the descriptions.'
          required: true
        - label: 'I have tried the `nightly` build first, if I was not already using it. This means the logs I provide are from the `nightly` build.'
          required: true
        - label: 'I have rebooted at least once after I saw the issue.'
          required: true
        - label: 'I have read the complete [changelog](https://github.com/mr-manuel/dbus-serialbattery/blob/master/CHANGELOG.md).'
          required: true
        - label: 'I have provided the logfiles in the correct format with a HUMAN READABLE timestamp by piping it through `tai64nlocal`.'
          required: true
        - label: 'I have clicked all checkboxes because I did not read the instructions.'
          required: false
