name: Support request
description: Report a bug that you found, e.g. something is not working as expected
# title: ""
labels: ["support"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Before opening a support request, please check first [How to troubleshoot](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/) and the [FAQ (Frequently Asked Questions)](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/faq/) page

        In the case you have difficulties to write in english, try the [deepl.com](https://www.deepl.com) translator.

        ## 🚨 IMPORTANT 🚨

        * Please carefully read all the instructions below including the descriptions! Very often we have to request the data again, because it was not provided in the first place.

        * Please try the `nightly` build first, if you are not already using it. It's very likely that the bug is already fixed. See [here](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/general/install#nightly-build) how to install it.

        * Did you reboot at least once after you saw the issue? If not, reboot and check if the issue still exists.

        * Please read the complete [changelog](https://github.com/mr-manuel/dbus-serialbattery/blob/master/CHANGELOG.md).

        * Make sure to provide the logfiles in the correct format with a READABLE timestamp.

  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: A clear and concise description of what the problem is. Paste also screenshots and pictures, if needed. The more informations you give, the faster we find a solution.
      placeholder: |
        NOTE: Paste the logfields in the appropriate field below.
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Installation method
      description: Select how you installed the driver.
      multiple: false
      options:
        - ⚠️ Choose your option ⚠️
        - Install script from the documentation
        - Install script present in the driver folder
        - SFTP upload
        - USB stick
        - Other (please describe in the last textfield how you installed the driver)

  - type: input
    id: driver_version_installed
    attributes:
      label: Driver version of the currently installed driver
      description: |
        Visible in the [driver log files](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/#driver-log-files) or in the remote console/GUI under `SerialBattery` -> `Device` -> `Firmware version`.

        ⚠️ **IMPORTANT:** Do not write `latest` and specify the exact version number, else we cannot help you.
      placeholder: e.g. v1.0.20230927beta
    validations:
      required: true

  - type: input
    id: driver_version_last_working
    attributes:
      label: Driver version of the last known working driver
      description: |
        Insert the version of the driver where the bug was not present. If you don't know, leave it empty.
      placeholder: e.g. v1.0.20230927beta
    validations:
      required: false

  - type: dropdown
    id: venus_os_device_type
    attributes:
      label: Venus OS device type
      description: Select your Venus OS device type.
      multiple: false
      # https://github.com/victronenergy/venus/wiki/machines
      options:
        - ⚠️ Choose your option ⚠️
        - CCGX
        - Cerbo GX
        - Ekrano GX
        - GX Card (integrated in the Victron device)
        - Octo GX
        - Raspberry Pi 2
        - Raspberry Pi 3
        - Raspberry Pi 4
        - Raspberry Pi 5
        - Raspberry Pi Zero 2W
        - Raspberry Pi Zero
        - VANcu GX
        - Venus_GX
    validations:
      required: true

  - type: input
    id: venus_os_version
    attributes:
      label: Venus OS version
      description: |
        Visible in the remote console/GUI under `Settings` -> `Firmware` -> `Firmware version`

        ⚠️ **IMPORTANT:** Do not write `latest` and specify the exact version number, else we cannot help you.
      placeholder: e.g. v3.60
    validations:
      required: true

  - type: dropdown
    id: bms_type
    attributes:
      label: BMS type
      description: Select your used BMS type.
      multiple: true
      # https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/general/supported-bms
      options:
        - ANT BMS
        - Daly BMS
        - Daren 485
        - ECS GreenMeter
        - EG4 LiFePower (Revov, Tian Power)
        - EG4 LL
        - Felicity
        - Hektec Modbus SmartBMS / YanYang BMS
        - HLPdata BMS4S
        - Jiabaida JDB BMS (LLT Power, Overkill Solar, Smart BMS)
        - JKBMS (Heltec BMS)
        - JKBMS Inverter (JKBMS PB Model)
        - Kilovault
        - LiTime
        - MNB spi BMS
        - Pace BMS
        - Renogy BMS
        - Seplos
        - Seplos v3
        - Sinowealth
        - Valence U-BMS
    validations:
      required: true

  - type: input
    id: cell_count
    attributes:
      label: Cell count
      description: Specify how many cells your battery has.
    validations:
      required: true

  - type: input
    id: battery_count
    attributes:
      label: Battery count
      description: Specify how many batteries/BMS are connected to your Venus OS.
    validations:
      required: true

  - type: dropdown
    id: connection_type
    attributes:
      label: Connection type
      description: Select how you connected your battery to the Venus OS device.
      multiple: false
      options:
        - ⚠️ Choose your option ⚠️
        - Serial USB adapter to TTL
        - Serial USB adapter to RS485
        - Raspberry Pi RS485 HAT
        - Bluetooth
        - CAN
    validations:
      required: true

  - type: dropdown
    id: usb_hub
    attributes:
      label: USB hub
      description: |
        Select if you use a USB hub to connect the Serial USB adapter to the Venus OS device.

        ⚠️ **IMPORTANT:** If you use a USB hub, try to connect the Serial USB adapter directly to the Venus OS device to see if the issue still exists.
      multiple: false
      options:
        - ⚠️ Choose your option ⚠️
        - No
        - Yes, no external power supply
        - Yes, with external power supply
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Config file
      description: |
        Paste your `config.ini` file here. See [here](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/general/install#settings-locationpath) where you can find it. DO NOT COPY the `config.default.ini` here. The content will be automatically formatted into code, so no need for backticks.
      render: ini
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output here. See [here](https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/#driver-log-files) how to get the driver log files. The content will be automatically formatted into code, so no need for backticks.
        ⚠️ **IMPORTANT:** Do not forget to pipe the output through `tai64nlocal`, if you don't copy the commands from the documentation.
      render: shell
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
      description: If you are using a USB hub, paste a link to it here. Leave empty, if you already said all.
